CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  oauth_provider VARCHAR(50) NOT NULL,
  oauth_uid VARCHAR(255) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  tanggal_dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY (oauth_provider, oauth_uid)
);

CREATE TABLE tugas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  teks VARCHAR(255) NOT NULL,
  selesai BOOLEAN NOT NULL DEFAULT FALSE,
  tanggal_dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);